 FROM node:22-alpine

 WORKDIR /usr/src/app

 USER root
 RUN npm install -g @nestjs/cli ts-node-dev

 # Ensure node owns the working directory
 RUN chown -R node:node /usr/src/app

 # Switch to non-root user
 USER node

 # Copy package files
 COPY --chown=node:node package*.json ./

 # Install deps
 RUN npm install

 # Copy rest of code
 COPY --chown=node:node . .

 EXPOSE 3000
 CMD ["npm", "run", "start:dev"]